import React from 'react';
import PropTypes from 'prop-types';

const PrintTemlate = ({ columns, rows }) => {
    
  return (
    <div>
      <table width="100%" cellspacing="0" style={{ borderCollapse: 'collapse', cellpadding: 0, border: 0 }}>
        <tr>
          <td width="250" align="left" style={{ padding: '5px' }} valign="top">
            &nbsp;
          </td>
          <td align="center" style={{ padding: '5px', textDecoration: 'underline', fontSize: '20px' }}>
            {/* <strong>{instituteName}</strong> */}
            <strong>SchoolPad</strong>
          </td>
          <td width="250" align="right" style={{ padding: '5px', color: '#000000', fontSize: '14px' }} class="textVerdana08" valign="top">
            {/* <strong>Generated: {dateString} {currentTime}</strong> */}
            <strong>Generated:Time/Date</strong>
          </td>
        </tr>
        <tr>
          <td colspan={3} className="textVerdana09" style={{ color: '#000000', textDecoration: 'underline' }} align="center">
            <strong>Transport stop Master<br /><br /><br /></strong>
          </td>
        </tr>
        <tr height="10px"></tr>
      </table>

      <table width="100%" cellspacing="0" style={{ borderCollapse: 'collapse', cellpadding: 0, border: 0 }}>
        <tr>
          {/* ... Loop over columns ... */}
          {columns.map((col, index) => (
            <td key={index} style={{ font: '13px arial', padding: '5px', borderBottom: '0px solid #000', borderLeft: '1px solid #000', borderTop: '1px solid #000',borderRight: index === columns.length - 1 ? '1px solid #000' : '0px solid #000', color: '#000',textAlign: 'center' }}><nobr><b>{col.name}</b></nobr></td>
          ))}
        </tr>
        {/* ... Loop over rows ... */}
        {rows.map((row, index) => (
          <tr key={index}>
             {columns.map((col, colIndex) => (
        <td key={colIndex} style={{ font: '13px arial', padding: '5px', borderBottom: '1px solid #000', borderLeft: '1px solid #000', borderTop: '1px solid #000', borderRight: colIndex === columns.length - 1 ? '1px solid #000' : '0px solid #000', color: '#000',textAlign: 'center' }}>
          <nobr>{row[col.field]}</nobr>
               </td>
               ))} 
        </tr>
           ))}
        <tr height="20px"></tr>
        <tr>
        <td colspan="3" className="textVerdana11" style={{ fontSize: '14px', color: '#000000', textDecoration: 'underline' }} align="left">
          <strong>Generated By : Employee Name</strong>
        </td>
        </tr>
      </table>
    </div>

  );
};

PrintTemlate.propTypes = {
  columns: PropTypes.arrayOf(PropTypes.object).isRequired,
  rows: PropTypes.arrayOf(PropTypes.object).isRequired
};

export default PrintTemlate;
